---
- name: selinux enable or disable
  hosts: db
  become: yes
  vars:
     status: permissive
  tasks:
     - name: changing SELinux from config file
       lineinfile:
           path: /etc/selinux/config
           regexp: '^SELINUX='
           line: 'SELINUX={{ status }}'
     - name: change directory