---
  - name: Install and configure tomcat
    hosts: all
    gather_facts: false
    become: yes

    vars:
      req_java: java-1.8.0-openjdk
      set_java: jre-1.8.0-openjdk

      req_tomcat_ver: 9.0.50
      tomcat_url: http://mirrors.estointernet.in/apache/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
      tomcat_port: 8090

    
    tasks:
      # Role1 -update_repos
      - name: Updating repos
        yum:
          name: "*"
          state: latest

      # Role 2= Install_java / var
      - name: Installing required java
        yum:
          name: "{{req_java}}"
          state: present

      - name: Setting default java
        alternatives:
          name: java
          link: /usr/bin/java
          path: /usr/lib/jvm/{{set_java}}/bin/java

     # Role 3 = Install_tomcat / var
      - name: Downloading required tomcat
        get_url:
          url: "{{tomcat_url}}"
          dest: /usr/local
      - name: Extracting downloaded tomcat
        unarchive:
          src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
          dest: /usr/local
          remote_src: yes

      - name: Renaming tomcat home
        command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest

      - name: Replacing default port with required port
        template:
          src: server.xml.j2
          dest: /usr/local/latest/conf/server.xml
      #notify: start_tomcat

      # Handler - start_tomcat
      - name: Starting tomcat
        shell:  nohup /usr/local/latest/bin/startup.sh & 
