---
 - hosts: localhost
   vars:
    x: 45
    my_name: "Kennedy"
   vars_prompt:
    - name: user_name
      prompt: Enter your user name 
      private: no
    - name: password
      prompt: Enter your password 
      private: yes
   gather_facts: false
   tasks:
   - debug:
      msg: "The username is: {{user_name}} and password is: {{password}}" 
