---
  - name: Simple play to install httpd or apache2
    hosts: group1
    gather_facts: true
    become: yes
    tasks:
    - name: Installing httpd using yum
      yum:
        name: httpd
        state: present
      when: ansible_distribution != "Ubuntu"
    - name: Installing apache2 using apt
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
